### ISSUE TITLE
questions about Figure 4 in FPE

### ISSUE THREAD

**Issue by ArsenLuca** [alibaba/EasyNLP#353]
![image](https://github.com/alibaba/EasyNLP/assets/23271554/625d8eb5-7aa0-4442-96d0-b38f47d89e23)
 I've two questions:
1. Two subfigure (As marked in blue boxes) in Figure 4 seems exactly identical, why it happens
2. What's the differences in algorithm between "No replacement" and "Direct Generation"

Thanks

**Comment by Bingyan-Liu** [comment]
1. They are the same image. To retain the spatial structure between the source and the target image, the upper part of this figure is generated based on replacing the self-attention map in layers 4-14.
2. In the upper part of Figure 4, "No replacement" indicates that there is no replacement of the cross-attention map from the source image; however, replacement of the self-attention map is included in order to preserve the spatial structure. In the lower part of Figure 4,"No replacement"="Direct Generation".

> ![image](https://private-user-images.githubusercontent.com/23271554/312362733-625d8eb5-7aa0-4442-96d0-b38f47d89e23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDg1NDQsIm5iZiI6MTcxMDQwODI0NCwicGF0aCI6Ii8yMzI3MTU1NC8zMTIzNjI3MzMtNjI1ZDhlYjUtN2FhMC00NDQyLTk2ZDAtYjM4ZjQ3ZDg5ZTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5MjQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYTA5ZWIxY2NjN2Y5NTBjOTQxZDM3MmYxNWM3ZTkxMzU1YmQ4MzE0NTJjNzZjODRlNTljNDM3ZDQ1MzY3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZbJm8CWs1hGWD2t3iN5XvM9qor44eYE9B86vWHuN_Y) I've two questions:
> 
> 1. Two subfigure (As marked in blue boxes) in Figure 4 seems exactly identical, why it happens
> 2. What's the differences in algorithm between "No replacement" and "Direct Generation"
> 
> Thanks
